# Generated by Django 5.2.8 on 2025-11-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('head', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
