# Generated by Django 5.2.8 on 2025-11-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArianHospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, help_text="Short role or specialty, e.g. 'Head of Emergency Care'", max_length=200)),
                ('qualifications', models.CharField(blank=True, help_text="Qualifications, e.g. 'MBChB, MMed'", max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.CharField(blank=True, help_text='Static path or URL to a headshot (optional)', max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
