# Generated by Django 5.2.8 on 2025-11-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArianHospitalApp', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, help_text='Optional site/hospital name', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(blank=True, help_text='Human readable opening hours', max_length=200)),
                ('extra', models.TextField(blank=True, help_text='Any extra contact or directions (HTML allowed)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
                'ordering': ['order'],
            },
        ),
    ]
